### ISSUE TITLE
EXTREME flicker on htc vive

### ISSUE THREAD

**Issue by ManuelGraf** [Cecropia/thehallaframe#7]
Whenever standing in any sideway, looking at the center of the hall, the view begins to split and you're actually seeing everything twice. This does not apply when you are facing a wall but if there are a lot of objects within the frustrum.

**Comment by Absulit** [comment]
I experienced this when you reported it, it seems it wasn't A-Frame but something from Oculus or Firefox in my case, now that it seems it has been fixed I've bumped the A-Frame version, please confirm everything is OK

**Comment by Absulit** [comment]
OK. Even the last version had a minor hiccup that required SteamVR to be fired prior its use. But it now works.
